### ISSUE TITLE
Action fails if 404 occurs

### ISSUE THREAD

**Issue by aeneasr** [ory/closed-reference-notifier#67]
**Describe the bug**

See: https://github.com/ory/cli/runs/2588241075?check_suite_focus=true

**To Reproduce**

Probably reference something that returns a 404?

**Expected behavior**

Maybe throw a warning but not error.

**Comment by zepatrik** [comment]
I assume this is caused by missing permissions, as the referenced issue is in a private repo. Should definitely not error but warn. I assume that no-one will actually see the warning though, maybe create an issue in that case? It needs some action anyway, either add an API token, or change the reference in case the issue/repo/... moved.

**Comment by aeneasr** [comment]
I think a warning is ok for now
